[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python main_integrated.py"
restartPolicyType = "always"
restartPolicyMaxRetries = 10

[services.web]
source = "."
buildCommand = "pip install -r requirements.txt"
startCommand = "python main_integrated.py"

[environment]
PORT = "8080"
TELEGRAM_TOKEN = "$TELEGRAM_TOKEN" 