[build]
# Forçar detecção Python
provider = "python"

[variables]
# Variáveis do ambiente
PORT = "8080"
PYTHONPATH = "/app"

[phases.setup]
# Instalar Python e pip
dependsOn = []
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
# Instalar dependências explicitamente
dependsOn = ["setup"]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[start]
# Comando de start explícito e direto
cmd = "python main.py" 