[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "python main.py"

[variables]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1" 