[build]
builder = "dockerFile"

[deploy]
startCommand = "python bot_v13_railway.py"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "never"

[env]
TELEGRAM_TOKEN = "${{ secrets.TELEGRAM_TOKEN }}"
OWNER_ID = "${{ secrets.OWNER_ID }}" 