[build]
builder = "nixpacks"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[environments.production]
variables = { PORT = "8080" }

[variables]
TELEGRAM_TOKEN = "${{TELEGRAM_TOKEN}}" 