[build]
builder = "nixpacks"

[deploy]
startCommand = "python bot_v13_railway.py"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"

[env]
TELEGRAM_TOKEN = "${{ secrets.TELEGRAM_TOKEN }}"
OWNER_ID = "${{ secrets.OWNER_ID }}" 